language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm-nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install